export default function Hero() {
  return (
    <section className="hero">
      <div className="wrap">
        <div>
          <div className="eyebrow">
            <span className="dot" />
            Connect once. AI runs the rest.
          </div>
          <h1>
            Connect your pages.
            <br />
            AI writes, designs
            <br />
            <em>and posts for you.</em>
          </h1>
          <p className="lede">
            Loopline connects to your social accounts, writes SEO-friendly
            titles and captions, generates banner images, publishes on your
            schedule, and reports back on what worked — all without you
            opening a design tool.
          </p>
          <div className="hero-ctas">
            <a href="/signup" className="btn btn-primary">
              Start free trial
            </a>
            <a href="#how-it-works" className="btn btn-ghost">
              See how it works
            </a>
          </div>
          <div className="trust-row">
            <div className="avatars">
              <div>JM</div>
              <div>AR</div>
              <div>TK</div>
              <div>+</div>
            </div>
            <span>Trusted by 4,200+ social teams</span>
          </div>
        </div>

        <div className="stack">
          <div className="post-card card-1">
            <div className="p-head">
              <div className="p-avatar" style={{ background: '#FFD9E4' }} />
              <div>
                <div className="p-name">Nourish Kitchen</div>
                <div className="p-handle">@nourishco</div>
              </div>
              <div className="p-platform" style={{ background: '#E7F7F3', color: 'var(--mint)' }}>
                Facebook
              </div>
            </div>
            <div className="p-body">
              Banner + caption auto-generated: "3 lunch preps under 400
              calories" — SEO title tuned for search.
            </div>
            <div className="p-footer">
              <span className="p-time">Auto-posted · 9:00am</span>
              <span className="p-status">Published</span>
            </div>
          </div>

          <div className="post-card card-2">
            <div className="p-head">
              <div className="p-avatar" style={{ background: '#DCD3F9' }} />
              <div>
                <div className="p-name">Fielder Studio</div>
                <div className="p-handle">@fielder.studio</div>
              </div>
              <div className="p-platform" style={{ background: '#EDEAFB', color: 'var(--violet-deep)' }}>
                LinkedIn
              </div>
            </div>
            <div className="p-body">
              Carousel banner generated by AI: "Why small agencies win big
              pitches" — 5 slides, brand colors matched.
            </div>
            <div className="p-footer">
              <span className="p-time">Auto-posted · 11:30am</span>
              <span className="p-status">Published</span>
            </div>
          </div>

          <div className="post-card card-3">
            <div className="p-head">
              <div className="p-avatar" style={{ background: '#FFE3B0' }} />
              <div>
                <div className="p-name">Marlow Coffee</div>
                <div className="p-handle">@marlow.coffee</div>
              </div>
              <div className="p-platform" style={{ background: '#FEECEE', color: '#C23558' }}>
                Instagram
              </div>
            </div>
            <div className="p-body">
              Generating banner and SEO caption for new cold-brew launch
              <span className="caret" />
            </div>
            <div className="p-footer">
              <span className="p-time">Generating now</span>
              <span className="p-status" style={{ background: '#EDEAFB', color: 'var(--violet-deep)' }}>
                AI working
              </span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}